---
title: IdeaCrew's EventSource Gem
baseURL: "/"
disableKinds: [taxonomy term]
languageCode: "en-us"
markup: map[tableofcontents:map[ordered:false]]
relativeURLs: true
showToc: true
theme: "docsy"
titleCaseStyle: "AP"
